/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Connect: typeof import('./components/Connect.vue')['default']
    Control: typeof import('./components/Control.vue')['default']
    Device: typeof import('./components/Device.vue')['default']
    Log: typeof import('./components/Log.vue')['default']
    Main: typeof import('./components/Main.vue')['default']
    PTT: typeof import('./components/PTT.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
